-- begin PANDORA_EVENT
alter table PANDORA_EVENT add constraint FK_PANDORA_EVENT_RELAPSE foreign key (RELAPSE_ID) references PANDORA_RELAPSE(ID)^
-- end PANDORA_EVENT

-- begin PANDORA_PATIENT
alter table PANDORA_PATIENT add constraint FK_PANDORA_PATIENT_DIAGNOS foreign key (DIAGNOS_ID) references PANDORA_DIAGNOSIS(ID)^
alter table PANDORA_PATIENT add constraint FK_PANDORA_PATIENT_THERAPY foreign key (THERAPY_ID) references PANDORA_THERAPY(ID)^
alter table PANDORA_PATIENT add constraint FK_PANDORA_PATIENT_EVENT foreign key (EVENT_ID) references PANDORA_EVENT(ID)^
alter table PANDORA_PATIENT add constraint FK_PANDORA_PATIENT_SURGERY foreign key (SURGERY_ID) references PANDORA_SURGERY(ID)^
alter table PANDORA_PATIENT add constraint FK_PANDORA_PATIENT_TREATMENT foreign key (TREATMENT_ID) references PANDORA_TREATMENT_RATING(ID)^
-- end PANDORA_PATIENT
-- begin PANDORA_THERAPY
alter table PANDORA_THERAPY add constraint FK_PANDORA_THERAPY_PROTOCOL foreign key (PROTOCOL_ID) references PANDORA_PROTOCOL(ID)^
alter table PANDORA_THERAPY add constraint FK_PANDORA_THERAPY_TC99_SCINTIGRAPHY foreign key (TC99_SCINTIGRAPHY_ID) references PANDORA_TC99_SCINTIGRAPHY(ID)^
alter table PANDORA_THERAPY add constraint FK_PANDORA_THERAPY_MYELOGRAM foreign key (MYELOGRAM_ID) references PANDORA_MYELOGRAM(ID)^
-- end PANDORA_THERAPY
-- begin PANDORA_TREATMENT_RATING
alter table PANDORA_TREATMENT_RATING add constraint FK_PANDORA_TREATMENT_RATING_EAR_RATING foreign key (EAR_RATING_ID) references PANDORA_EAR_RATING(ID)^
-- end PANDORA_TREATMENT_RATING
